### ISSUE TITLE
check_2_1_8

### ISSUE THREAD

**Issue by arjunsbabu** [neuvector/kubernetes-cis-benchmark#17]
As per CIS document "Verify that if the  --make-iptables-util-chains argument exists then it is set to true"
But in the script it will only make pass if --make-iptables-util-chains=false
Kindly review and correct me if iam wrong

**Comment by yanguo2111** [comment]
please double check. In the script file worker_1_kubelet.sh line  62:
if check_argument 'kubelet' '--make-iptables-util-chains=true' >/dev/null 2>&1; then
it only passes when --make-iptables-util-chains=true

**Comment by becitsthere** [comment]
This issue has been closed due to inactivity.
