### ISSUE TITLE
Enable to specify command for check_argument externally

### ISSUE THREAD

**Issue by mwieczorek** [neuvector/kubernetes-cis-benchmark#19]
Right now the command is hardcoded in every check in, f.e. in https://github.com/neuvector/kubernetes-cis-benchmark/blob/master/1.8/worker/worker_1_kubelet.sh

`check_argument 'kubelet'`

If I run kubelet as hyperkube it will show me wrong results. 

I propose to enable to pass that command externally.
F.e.:
Add 
`CIS_KUBELET_CMD=${CIS_KUBELET_CMD:-kubelet}`
and then
`check_argument '$CIS_KUBELET_CMD'`

In such case I could run:
```
export CIS_KUBELET_CMD="hyperkube kubelet"
./worker.sh 1.8
```

**Comment by yanguo2111** [comment]
please help to check my pull request.
