### ISSUE TITLE
apiserver empty '--service-account-key-file' is valid if '--tls-private-key-file' is set

### ISSUE THREAD

**Issue by antoineco** [neuvector/kubernetes-cis-benchmark#3]
If unspecified, `--service-account-key-file` defaults to `--tls-private-key-file`.

**Comment by yanguo2111** [comment]
we follow the spec:
 To ensure that the keys for service account tokens could be rotated as needed, a separate public/private key pair should be used for signing service account tokens. Hence, the public key should be specified to the apiserver with --service-account-key-file.

**Comment by antoineco** [comment]
In that case it's correct indeed, thanks for clarifying!
